obj-$(CONFIG_FB_ROCKCHIP) += rk_fb.o rkfb_sysfs.o lcdc/ screen/
obj-$(CONFIG_RK_TRSM) += transmitter/
obj-$(CONFIG_RGA_RKPX2) += rga/
obj-$(CONFIG_RK_HDMI) += hdmi/
obj-$(CONFIG_RK_VGA) += vga/
obj-y +=disp/
